name: learn_tanah
description: Learn Tanah

publish_to: 'none'

version: 2.0.6+4306

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  localstorage: ^5.0.0
  path_provider: ^2.1.0
  http: ^1.2.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/html/
    - assets/html/Amos/
    - assets/html/css/
    - assets/html/Chabakuk/
    - assets/html/Daniel/
    - assets/html/Chagi/
    - assets/html/DivreyHayamimI/
    - assets/html/DivreyHayamimII/
    - assets/html/Esther/
    - assets/html/Eycha/
    - assets/html/Eyov/
    - assets/html/Ezra/
    - assets/html/Hoshea/
    - assets/html/js/
    - assets/html/Kohelet/
    - assets/html/Malachi/
    - assets/html/MelachimI/
    - assets/html/MelachimII/
    - assets/html/Micha/
    - assets/html/Mishley/
    - assets/html/Nachum/
    - assets/html/Nechamia/
    - assets/html/Ovadia/
    - assets/html/Rut/
    - assets/html/ShirHashirim/
    - assets/html/ShmuelI/
    - assets/html/ShmuelII/
    - assets/html/Shoftim/
    - assets/html/Tehilim/
    - assets/html/Tzefanya/
    - assets/html/Yechezkel/
    - assets/html/Yehoshua/
    - assets/html/Yirmiya/
    - assets/html/Yishaya/
    - assets/html/Yoel/
    - assets/html/Yona/
    - assets/html/Zecharia/
